apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-backend
  labels:
    app: baseline-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseline-backend
  template:
    metadata:
      labels:
        app: baseline-backend
    spec:
      containers:
        - name: backend
          image: baseline-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: FRONTEND_URL
              value: "http://baseline-frontend:5173"
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/baseline-autopilot"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: NODE_ENV
              value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: baseline-backend
  labels:
    app: baseline-backend
spec:
  type: ClusterIP
  selector:
    app: baseline-backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
